theme: jekyll-theme-cayman
title: Hello ! I am Subhayan Mukherjee.
description: This website has my Project summaries with links to related First author publications / Preprints (free), among other things.
plugins:
  - jekyll-seo-tag
