theme: jekyll-theme-cayman
title: Hello ! I am Subhayan Mukherjee.
description: Check out my Project summaries with links to related First author publications / Preprints (free), Codes, etc.
plugins:
  - jekyll-seo-tag
